services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  conv_lpi:
    build:
      context: ./conv
      dockerfile: Dockerfile.conv_lpi
    environment:
      - CONV_CONTEXT=LPI
    env_file:
      - ./.env
    volumes:
      - ./helper:/app/helper
      - ./logger:/app/logger
      - "C:/Users/oelawad/Desktop/Software/2412511_data/lpi/data:/app/files/input_100hz"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/lpi/data_completed:/app/files/finished_100hz"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/lpi/stats:/app/files/stats_100hz"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/lpi/failed:/app/files/failed_100hz"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/logs:/app/logs"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL",
        "redis-cli -h ${REDIS_HOST:-redis} -p ${REDIS_PORT:-6379} \
        GET ${HEALTH_CONTAINER_CONV_LPI:-health:container_conv_lpi} | grep -q '^1$'"]
      interval: 30s
      timeout: 5s
      retries: 3

  conv_sens:
    build:
      context: ./conv
      dockerfile: Dockerfile.conv_sens
    environment:
      - CONV_CONTEXT=SENS
    env_file:
      - ./.env
    volumes:
      - ./helper:/app/helper
      - ./logger:/app/logger
      - "C:/Users/oelawad/Desktop/Software/2412511_data/sensical/data:/app/files/input"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/sensical/data_completed:/app/files/finished"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/sensical/stats:/app/files/stats"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/sensical/failed:/app/files/failed"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/logs:/app/logs"
    restart: unless-stopped
    
  conv_mist:
    build:
      context: ./conv
      dockerfile: Dockerfile.conv_mist
    environment:
      - CONV_CONTEXT=MIST
    env_file:
      - ./.env
    volumes:
      - ./helper:/app/helper
      - ./logger:/app/logger
      - "C:/Users/oelawad/Desktop/Software/2412511_data/mistras/data:/app/files/input"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/mistras/data_completed:/app/files/finished"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/mistras/stats:/app/files/stats"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/mistras/failed:/app/files/failed"
      - "C:/Users/oelawad/Desktop/Software/2412511_data/logs:/app/logs"
    restart: unless-stopped

volumes:
  redis_data:
