services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  converter:
    build:
      context: ./conv_lpi
      dockerfile: Dockerfile.conv_lpi
    container_name: 2412511_conv_lpi
    env_file:
      - ./.env
    volumes:
      - ./helper:/app/helper
      - ./logger:/app/logger
      - "/home/omarea/Programs/VSCode/2412511_data/100hz/input:/app/files/input_100hz"
      - "/home/omarea/Programs/VSCode/2412511_data/100hz/finished:/app/files/finished_100hz"
      - "/home/omarea/Programs/VSCode/2412511_data/100hz/stats:/app/files/stats_100hz"
      - "/home/omarea/Programs/VSCode/2412511_data/100hz/failed:/app/files/failed_100hz"
      - "/home/omarea/Programs/VSCode/2412511_data/logs:/app/logs"
    restart: unless-stopped

volumes:
  redis_data:
