services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  converter:
    build:
      context: ./conv_lpi
      dockerfile: Dockerfile.conv_lpi
    container_name: 2412511_conv_lpi
    env_file:
      - ./.env
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL",
        "redis-cli -h ${REDIS_HOST:-redis} -p ${REDIS_PORT:-6379} \
        GET ${HEARTBEAT_KEY_CONVERTER:-heartbeat:converter} | grep -q '^0$'"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
