FROM python:3.12.9-slim

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    openssh-client \
    sshpass \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

RUN mkdir -p files/finished_100hz \
            files/finished_1hz \
            logs

VOLUME ["/app/files/finished_100hz", \
        "/app/files/finished_1hz", \
        "/app/logs"]

CMD ["python", "main.py"]